### ISSUE TITLE
ToandFro question

### ISSUE THREAD

**Issue by renderit** [Kafiil/Codefights#1]
Hi. Good work here. Curious to know, were you able to solve this question on code fights? : https://github.com/agusmakmun/CodeFights-1/blob/master/tasks/toAndFro.md 
I couldn't.

**Comment by Kafiil** [comment]
Hi, this is how I solved it in Javascript : 
```javascript
function toAndFro(a, b, t) {

  var len = Math.abs(b - a);
  t %= (2 * len);
  if (t <= len) {
    return a + (b - a) / Math.abs(b - a) * t;
  }
  else {
    t -= len;
    return b - (b - a) / Math.abs(a - b) * t;
  }
}

**Comment by renderit** [comment]
@Kafiil Interesting thanks for sharing. However I don't understand the concept. :(  Is this some algorithm I can look up?

**Comment by Kafiil** [comment]
It is a very simple logic concept, give it a try and see ;)
